//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUResorts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public int GID { get; set; }
        public string EmpRoleID { get; set; }
        public string Password { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Employee_Roles Employee_Roles { get; set; }
    }
}
