//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUResorts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Charges = new HashSet<Charge>();
        }
    
        public int RID { get; set; }
        public int GID { get; set; }
        public int room { get; set; }
        public System.DateTime DateReserved { get; set; }
        public System.DateTime reservStart { get; set; }
        public System.DateTime reservEnd { get; set; }
        public Nullable<System.DateTime> CheckIN { get; set; }
        public Nullable<System.DateTime> CheckOUT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Charge> Charges { get; set; }
        public virtual Person Person { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
